---
global:
  checkNewVersion: false
  sendAnonymousUsage: false
log:
  level: DEBUG
# api:
#   dashboard: true
#   insecure: true
entryPoints:
  web:
    address: :80
    # <--
    #   to atomatically redirect to https remove the address field above,
    #   and uncomment next section
    # -->
    # http:
    #   redirections:
    #     entryPoint:
    #       to: websecure
    #       scheme: https
  websecure:
    address: :443
certificatesResolvers:
  cloudflare:
    acme:
      # add your email below
      email: ""
      storage: /var/traefik/certs/cloudflare-acme.json
      caServer: "https://acme-v02.api.letsencrypt.org/directory"
      keyType: EC256
      dnsChallenge:
        provider: cloudflare
        resolvers:
          - "1.1.1.1:53"
          - "8.8.8.8:53"
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
